# Start with a base image containing runtime Java and Maven
FROM maven:3.8.4-openjdk-17 as build

# Copy the project files into the container
COPY src /nguyentoan/spring-mvc/src
COPY pom.xml /nguyentoan/spring-mvc

# Set the working directory
WORKDIR /nguyentoan/spring-mvc

# Bulid the application as a WAR file and skip tests
RUN mvn clean package -DskipTests

FROM openjdk:17-slim

# Copy WAR file to the webapps directory in Tomcat
# Ensure that the path to the WAR file matches the actual file name generated by Maven
COPY --from=build /nguyentoan/spring-mvc/target/*.war /nguyentoan/spring-mvc/app.war

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/nguyentoan/spring-mvc/app.war"]